# This is a basic workflow to help you get started with Actions
#
# things to fixa at some point
# - add in latest_pyside_gui
# - latest_pyqt_gui for python 3.9 (currently vtk is not on PyPi)
#   - currently a duplicate build is running
name: CI

# Controls when the action will run.
#on: [push]
on:
  push:
    paths-ignore:
      #- ".github/**"
      - "*.md"
#    branches:
#      - master
  pull_request:
    branches: [ master ]

#on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#=======================================================================================================
  windows_build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
         #python-version: [3.9]  # testing
         python-version: [3.7, 3.8, 3.9]   # TODO: should be enabled...disabled for testing...
         os: [windows-latest]
         # , macos-latest, windows-latest
         mode: ['latest', 'latest_colorama'] # , 'windows-latest_colorama'
      fail-fast: false

    #--------------------------------------------------------------------------------------------------
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print environment variables exposed by GitHub
        run: |
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "GITHUB_ACTION=$GITHUB_ACTION"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8
         #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pip list

        #mode: ['latest', 'latest_colorama']
      - name: Install latest packages - ${{ matrix.mode }}
        if: ${{ matrix.mode == 'latest_colorama' || matrix.mode == 'windows-latest_colorama'}}
        run: |
          pip install colorama ipython psutil

#-----------------------------------------------------------------------------------

      - name: Install dependencies
        run: |
         pip install codecov
         python setup.py develop

      - name: List dependencies
        run: |
         pip list

      - name: Run Tests
        run: |
         #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         python cpylog/test_log.py
         coverage run cpylog/test_log.py

      - name: Upload coverage
        run: |
         codecov
#==================================================================================================
  linux_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
         #python-version: [3.9]  # testing
         python-version: [3.7, 3.8, 3.9]   # TODO: should be enabled...disabled for testing...
         os: [ubuntu-latest]
         # , macos-latest, windows-latest
         mode: ['latest', 'latest_colorama'] # , 'windows-latest_colorama'
      fail-fast: false

    #--------------------------------------------------------------------------------------------------
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print environment variables exposed by GitHub
        run: |
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "GITHUB_ACTION=$GITHUB_ACTION"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8
         #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pip list

        #mode: ['latest', 'latest_colorama']
      - name: Install latest packages - ${{ matrix.mode }}
        if: ${{ matrix.mode == 'latest_colorama' || matrix.mode == 'windows-latest_colorama'}}
        run: |
          pip install colorama ipython psutil

#-----------------------------------------------------------------------------------

      - name: Install dependencies
        run: |
         pip install codecov
         python setup.py develop

      - name: List dependencies
        run: |
         pip list

      - name: Run Tests
        run: |
         #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         python cpylog/test_log.py
         coverage run cpylog/test_log.py

      - name: Upload coverage
        run: |
         codecov
