# .github/workflows/pypi-publish.yml
# read this first
#   https://docs.pypi.org/trusted-publishers/
#
# some examples:
#   https://github.com/ckan/ckan/blob/master/.github/workflows/publish-pypi.yml
#   https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d
name: Publish to PyPI

jobs:
  pypi-publish:
    name: Build distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cpylog
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build tools
      run: pip install build

    - name: Build distributions
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
